Repository lambdaclass/mirra_backend, pull requests merged in 2024-04, with the labels that each got.

#373 [Rewrite Battle] Implement Effects
  apps/champions/lib/champions/battle/simulator.ex
  priv/repo/seeds.exs
Labels: waiting on pr, do not merge

#305 [GH-309] add valtimer teleport
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game/skill.ex
  apps/arena/lib/arena/game_updater.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/lib/physics.ex
  apps/arena/native/physics/src/lib.rs
  apps/arena/priv/config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/serialization/messages.proto
Labels: waiting on, do not merge

#444 replace h4ck ultimate for pool mechanic
  apps/arena/priv/config.json
Labels: waiting on PR

#425 Effect refactor: Reset and reapply player effects on each tick (and some other cool things)
  apps/arena/lib/arena/configuration.ex
  apps/arena/lib/arena/entities.ex
  apps/arena/lib/arena/game/effect.ex
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game/skill.ex
  apps/arena/lib/arena/game_updater.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/priv/config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/serialization/messages.proto
Labels: do not merge

#412 Scale up map and obstacles reposition
  apps/arena/priv/config.json
Labels: waiting on PR

#482 Fix protobuf message names for tags and modifiers
  apps/champions/lib/champions/battle/simulator.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/serialization/gateway.proto
Labels: bug

#473 Refactor Gateway Messages
  apps/champions/lib/champions/battle/simulator.ex
  apps/gateway/lib/gateway/champions_socket_handler.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/serialization/gateway.proto
Labels: waiting on PR
