Repository lambdaclass/mirra_backend, pull requests merged in 2024-06, with the labels that each got.

#627 [GH-618] Triangulate concave polygons
  apps/arena/docs/collision-detection.md
  apps/arena/docs/images/Point inside triangle.jpg
  apps/arena/lib/physics.ex
  apps/arena/native/physics/src/collision_detection.rs
  apps/arena/native/physics/src/collision_detection/ear_clipping.rs
  apps/arena/native/physics/src/lib.rs
  apps/arena/native/physics/src/map.rs
  apps/arena/priv/config.json
  apps/game_client/assets/js/hooks/board_game.js
Labels: champions

#619 [GH-616] Add client config json
  apps/arena/lib/arena/configuration.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/priv/client_config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/bot_manager/lib/protobuf/messages.pb.ex
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/serialization/messages.proto
Labels: waiting on PR, champions

#655 [GH-596] Bounties
  apps/arena/lib/arena/application.ex
  apps/arena/lib/arena/entities.ex
  apps/arena/lib/arena/game_bounties_fetcher.ex
  apps/arena/lib/arena/game_socket_handler.ex
  apps/arena/lib/arena/game_tracker.ex
  apps/arena/lib/arena/game_updater.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/priv/config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/bot_manager/lib/protobuf/messages.pb.ex
  apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
  apps/game_backend/lib/game_backend/matches.ex
  apps/game_backend/lib/game_backend/quests/quest.ex
  apps/game_backend/lib/game_backend/quests/user_quest.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/curse_of_mirra/quests_descriptions.json
  apps/game_backend/priv/repo/migrations/20240524202403_rename_dailyquest_to_userquest.exs
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/gateway/lib/gateway/controllers/curse_of_mirra/quest_controller.ex
  apps/gateway/lib/gateway/controllers/fallback_controller.ex
  apps/gateway/lib/gateway/router.ex
  apps/serialization/messages.proto
Labels: champions

#663 [GH-425] [DUNGEON] Dungeon Levels config
  apps/champions/lib/champions/config.ex
  apps/champions/priv/dungeon_campaign.json
  apps/game_backend/lib/game_backend/campaigns.ex
  apps/game_backend/lib/game_backend/campaigns/level.ex
  priv/repo/seeds.exs
Labels: autobattler

#647 [GH-404] lowest and highest stat targeting strategies
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/test/battle_test.exs
  apps/game_backend/lib/game_backend/units/skills/mechanics/targeting_strategies/target_strategy.ex
Labels: autobattler

#658 [GH-470] [Dungeon] Add tests for dungeon buffs/upgrades
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/test/battle_test.exs
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/kaline_tree_level.ex
  apps/gateway/lib/gateway/champions_socket_handler.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/gateway/test/champions_test.exs
  apps/gateway/test/support/socket_tester.ex
  apps/serialization/gateway.proto
  priv/repo/seeds.exs
Labels: autobattler

#683 Fix failing dungeon test
  apps/champions/lib/champions/users.ex
  apps/gateway/test/champions_test.exs
Labels: autobattler

#677 [GH-463] fixes to levels with costs
  apps/champions/lib/champions/config.ex
  apps/game_backend/lib/game_backend/campaigns.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/serialization/gateway.proto
Labels: autobattler

#668 [GH-443] [Dungeon] [Config] Create DungeonSettlementLevel config json import
  apps/champions/lib/champions/config.ex
  apps/champions/lib/champions/users.ex
  apps/champions/priv/dungeon_settlement_levels.json
  apps/game_backend/lib/game_backend/campaigns/rewards/afk_reward_rate.ex
  apps/game_backend/lib/game_backend/rewards.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/dungeon_settlement_level.ex
  apps/game_backend/priv/repo/migrations/20240605204558_rename_rate_to_daily_rate.exs
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/gateway/test/champions_test.exs
  apps/serialization/gateway.proto
  priv/repo/seeds.exs
Labels: autobattler

#631 [GH-595] Prestige ranking
  apps/arena/lib/arena/game_tracker.ex
  apps/game_backend/lib/game_backend/curse_of_mirra/matches.ex
  apps/game_backend/lib/game_backend/curse_of_mirra/users.ex
  apps/game_backend/lib/game_backend/units/unit.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/priv/arena_prestige_ranks.json
  apps/game_backend/priv/currencies_rules.json
  apps/game_backend/priv/repo/migrations/20240517093111_add_prestige_system_tables.exs
  apps/gateway/lib/gateway/controllers/curse_of_mirra/match_results_controller.ex
  apps/gateway/lib/gateway/router.ex
  config/runtime.exs
Labels: champions

#651 [GH-638] Add store table
  apps/game_backend/lib/game_backend/curse_of_mirra/config.ex
  apps/game_backend/lib/game_backend/items.ex
  apps/game_backend/lib/game_backend/items/item_template.ex
  apps/game_backend/lib/game_backend/stores.ex
  apps/game_backend/lib/game_backend/stores/store.ex
  apps/game_backend/priv/repo/migrations/20240524161740_add_store_table.exs
  apps/game_backend/priv/stores_config.json
  apps/gateway/lib/gateway/controllers/curse_of_mirra/item_controller.ex
  apps/gateway/lib/gateway/controllers/curse_of_mirra/store_controller.ex
  apps/gateway/lib/gateway/router.ex
  priv/repo/seeds.exs
Labels: champions

#667 [GH-359] [CONFIG] Implement campaign config
  apps/champions/lib/champions/config.ex
  apps/champions/priv/main_campaign.json
  apps/champions/priv/super_campaigns.json
  apps/game_backend/lib/game_backend/campaigns.ex
  apps/game_backend/lib/game_backend/campaigns/campaign.ex
  apps/game_backend/lib/game_backend/campaigns/level.ex
  apps/game_backend/lib/game_backend/campaigns/super_campaign.ex
  apps/game_backend/priv/repo/migrations/20240529214325_add_is_boss_stage_field_to_level.exs
  apps/game_backend/priv/repo/migrations/20240530142035_add_super_campaign_unique_index.exs
  apps/gateway/test/champions_test.exs
  priv/repo/seeds.exs
Labels: autobattler

#662 [GH-399] Deal damage over time
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/priv/skills.json
  apps/champions/test/battle_test.exs
  apps/champions/test/support/test_utils.ex
  apps/game_backend/lib/game_backend/units/skills/mechanics/effect.ex
Labels: autobattler

#681 [GH-439] Currency Capping
  apps/champions/lib/champions/users.ex
  apps/champions/priv/dungeon_settlement_levels.json
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/currencies.ex
  apps/game_backend/lib/game_backend/users/currencies/user_currency_cap.ex
  apps/game_backend/lib/game_backend/users/dungeon_settlement_level.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/repo/migrations/20240605134407_add_user_currency_caps.exs
  apps/game_backend/priv/repo/migrations/20240605184601_rename_supply_limit_to_supply_cap.exs
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/gateway/test/champions_test.exs
  apps/serialization/gateway.proto
Labels: autobattler

#665 [GH-640] Endpoint authentication
  .github/workflows/central-brazil-testing-deploy.yml
  .github/workflows/central-europe-testing-deploy.yml
  apps/arena/lib/arena/application.ex
  apps/arena/lib/arena/authentication/gateway_signer.ex
  apps/arena/lib/arena/authentication/gateway_token_manager.ex
  apps/arena/lib/arena/game_socket_handler.ex
  apps/arena/lib/arena/quick_game_handler.ex
  apps/arena/lib/arena/socket_handler.ex
  apps/arena/mix.exs
  apps/game_backend/lib/game_backend/curse_of_mirra/matches.ex
  apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
  apps/game_backend/lib/game_backend/matches/arena_match_result.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/google_user.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/repo/migrations/20240530162101_replace_google_user_with_user.exs
  apps/game_client/assets/js/hooks/game_queue.js
  apps/game_client/lib/game_client/client_socket_handler.ex
  apps/game_client/lib/game_client_web/controllers/auth_controller.ex
  apps/game_client/lib/game_client_web/controllers/page_html/home.html.heex
  apps/game_client/lib/game_client_web/live/pages/board/game_queue.ex
  apps/game_client/lib/game_client_web/live/pages/board/game_queue.html.heex
  apps/game_client/lib/game_client_web/live/pages/board/show.ex
  apps/game_client/lib/game_client_web/router.ex
  apps/gateway/lib/gateway/auth/token_manager.ex
  apps/gateway/lib/gateway/controllers/auth_controller.ex
  apps/gateway/lib/gateway/controllers/curse_of_mirra/user_controller.ex
  apps/gateway/lib/gateway/router.ex
  apps/gateway/mix.exs
  config/config.exs
  config/dev.exs
  config/runtime.exs
  devops/deploy.sh
Labels: do not merge, champions

#691 Limit amount of bounties sent to the client
  apps/arena/lib/arena/game_updater.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/priv/config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/bot_manager/lib/protobuf/messages.pb.ex
  apps/game_backend/priv/curse_of_mirra/quests_descriptions.json
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/serialization/messages.proto
Labels: waiting on PR
