Repository lambdaclass/mirra_backend, pull requests merged in 2024-05, with the labels that each got.

#533 AFK reward rates in kaline tree
  apps/champions/lib/champions/campaigns.ex
  apps/champions/lib/champions/users.ex
  apps/game_backend/lib/game_backend/campaigns.ex
  apps/game_backend/lib/game_backend/campaigns/level.ex
  apps/game_backend/lib/game_backend/campaigns/rewards/afk_reward_rate.ex
  apps/game_backend/lib/game_backend/campaigns/rewards/currency_reward.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/kaline_tree_level.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/repo/migrations/20240419190027_add_kaline_tree_level_to_user.exs
  apps/game_backend/priv/repo/migrations/20240426200343_move_afk_rewards_increment_to_kaline_tree_level.exs
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/gateway/test/champions_test.exs
  apps/serialization/gateway.proto
  priv/repo/seeds.exs
Labels: waiting on PR

#456 [GH-409] Leave matchmaking lobby
  apps/arena/lib/arena/game_launcher.ex
  apps/arena/lib/arena/quick_game_handler.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/lib/arena/socket_handler.ex
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/bot_manager/lib/protobuf/messages.pb.ex
  apps/game_client/assets/js/hooks/game_queue.js
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/serialization/messages.proto
Labels: waiting on PR

#390 Dynamic execution duration for leap
  apps/arena/lib/arena/game/effect.ex
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game/skill.ex
  apps/arena/lib/physics.ex
  apps/arena/native/physics/src/lib.rs
  apps/arena/priv/config.json
Labels: curse

#608 [GH-607] Only spawn bots if player is alive
  apps/arena/lib/arena/game_socket_handler.ex
Labels: curse

#593 [GH-429] Dungeon Settlement Levels
  apps/champions/lib/champions/users.ex
  apps/game_backend/docs/game_backend_classes.svg
  apps/game_backend/lib/game_backend/campaigns/rewards/afk_reward_rate.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/dungeon_settlement_level.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/repo/migrations/20240510133920_add_dungeon_settlement_level.exs
  apps/gateway/lib/gateway/champions_socket_handler.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/gateway/test/champions_test.exs
  apps/gateway/test/support/socket_tester.ex
  apps/serialization/gateway.proto
  priv/repo/seeds.exs
Labels: champions

#578 [GH-525] Track match data
  apps/arena/lib/arena/application.ex
  apps/arena/lib/arena/game_tracker.ex
  apps/arena/lib/arena/game_updater.ex
  apps/game_backend/lib/game_backend/matches.ex
  apps/game_backend/lib/game_backend/matches/arena_match_result.ex
  apps/gateway/lib/gateway/controllers/arena/match_results_controller.ex
  apps/gateway/lib/gateway/router.ex
Labels: curse

#603 [GH-599] Add crates to config
  apps/arena/priv/config.json
Labels: do not merge, curse

#562 Improve loadtest app part three
  .github/workflows/loadtest-brazil-client-deploy.yml
  .github/workflows/loadtest-europe-client-deploy.yml
  apps/arena/lib/arena/game_launcher.ex
  apps/arena_load_test/lib/arena_load_test/game_socket_handler.ex
  apps/arena_load_test/lib/arena_load_test/socket_handler.ex
  apps/arena_load_test/lib/arena_load_test/socket_supervisor.ex
  apps/arena_load_test/lib/arena_load_test/utils.ex
  devops/deploy.sh
Labels: curse

#587 [GH-586] Fix zone killfeed
  apps/arena/lib/arena/game_updater.ex
Labels: curse

#564 Stat override message
  apps/champions/lib/champions/battle/simulator.ex
  apps/gateway/lib/gateway/champions_socket_handler.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/serialization/gateway.proto
Labels: waiting on PR, champions

#609 [GH-601] Track more match data
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game_tracker.ex
  apps/arena/lib/arena/game_updater.ex
  apps/game_backend/lib/game_backend/matches/arena_match_result.ex
  apps/game_backend/priv/repo/migrations/20240513180434_add_more_match_results_data.exs
Labels: curse

#602 [GH-583] Add daily rewards
  apps/arena/docs/src/configuration/daily_rewards_rules.md
  apps/game_backend/lib/game_backend/rewards.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/lib/game_backend/utils.ex
  apps/game_backend/priv/daily_rewards_rules.json
  apps/game_backend/priv/repo/migrations/20240510172559_add_daily_rewards_fields_to_user.exs
  apps/gateway/lib/gateway/controllers/curse_of_mirra/currency_controller.ex
  apps/gateway/lib/gateway/controllers/curse_of_mirra/user_controller.ex
  apps/gateway/lib/gateway/controllers/fallback_controller.ex
  apps/gateway/lib/gateway/controllers/user_controller.ex
  apps/gateway/lib/gateway/router.ex
  config/runtime.exs
Labels: curse

#610 [GH-606] Make pools damage the crates
  apps/arena/lib/arena/entities.ex
  apps/arena/lib/arena/game/effect.ex
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game_updater.ex
Labels: curse

#598 [GH-580] Fake Item and Traps
  apps/arena/lib/arena/entities.ex
  apps/arena/lib/arena/game/item.ex
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game/skill.ex
  apps/arena/lib/arena/game/trap.ex
  apps/arena/lib/arena/game_updater.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/native/physics/src/map.rs
  apps/arena/priv/config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/bot_manager/lib/protobuf/messages.pb.ex
  apps/game_client/assets/js/hooks/board_game.js
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/game_client/lib/game_client_web/live/pages/board/show.ex
  apps/serialization/messages.proto
Labels: curse

#613 [GH-633] Add quest rewards functionality
  apps/game_backend/lib/game_backend/curse_of_mirra/quests.ex
  apps/game_backend/lib/game_backend/matches.ex
Labels: curse

#614 [GH-426] Add Dungeon Mode
  apps/champions/lib/champions/battle.ex
  apps/game_backend/lib/game_backend/campaigns.ex
  apps/game_backend/lib/game_backend/campaigns/level.ex
  apps/game_backend/priv/repo/migrations/20240514160226_add_dungeon_fields_to_level.exs
  apps/gateway/lib/gateway/champions_socket_handler.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/gateway/test/champions_test.exs
  apps/serialization/gateway.proto
  priv/repo/seeds.exs
Labels: waiting on PR, champions

#592 [GH-591] Allow movement while executing skills
  apps/arena/lib/arena/game/player.ex
  apps/arena/lib/arena/game/skill.ex
  apps/arena/lib/arena/game_socket_handler.ex
  apps/arena/lib/arena/game_updater.ex
  apps/arena/lib/arena/serialization/messages.pb.ex
  apps/arena/priv/config.json
  apps/arena_load_test/lib/arena_load_test/serialization/messages.pb.ex
  apps/bot_manager/lib/protobuf/messages.pb.ex
  apps/game_client/assets/js/protobuf/messages_pb.js
  apps/game_client/lib/game_client/protobuf/messages.pb.ex
  apps/serialization/messages.proto
Labels: curse

#588 [GH-327] Add Speed
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/lib/champions/units.ex
  apps/champions/test/battle_test.exs
Labels: champions

#617 [GH-431] Add currency cost to levels
  apps/champions/lib/champions/battle.ex
  apps/game_backend/lib/game_backend/campaigns/level.ex
  apps/game_backend/priv/repo/migrations/20240514200245_add_currency_cost_to_levels.exs
  apps/gateway/lib/gateway/champions_socket_handler.ex
  apps/gateway/lib/gateway/serialization/gateway.pb.ex
  apps/serialization/gateway.proto
  priv/repo/seeds.exs
Labels: champions

#575 [GH-322] Implement untargetable tag
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/test/battle_test.exs
Labels: champions

#644 [GH-637] Add endpoints to equip skin to character
  apps/arena/lib/arena/configuration.ex
  apps/arena/priv/config.json
  apps/game_backend/lib/game_backend/curse_of_mirra/config.ex
  apps/game_backend/lib/game_backend/curse_of_mirra/users.ex
  apps/game_backend/lib/game_backend/items.ex
  apps/game_backend/lib/game_backend/items/item_template.ex
  apps/game_backend/lib/game_backend/units.ex
  apps/game_backend/lib/game_backend/units/characters.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/characters_config.json
  apps/game_backend/priv/items_templates.json
  apps/game_backend/priv/repo/migrations/20240522182851_add_purchasable_and_characters_to_items_templates.exs
  apps/gateway/lib/gateway/controllers/curse_of_mirra/character_controller.ex
  apps/gateway/lib/gateway/controllers/curse_of_mirra/item_controller.ex
  apps/gateway/lib/gateway/controllers/fallback_controller.ex
  apps/gateway/lib/gateway/router.ex
  priv/repo/seeds.exs
Labels: champions

#649 [GH-589] Fix valtimer walking instead of teleporting when teleporting inside cannon rock
  apps/arena/priv/config.json
Labels: champions

#628 [GH-321] Silence Status Effect
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/test/battle_test.exs
Labels: autobattler

#632 [GH-428] Implement Buffs for Dungeon
  apps/champions/lib/champions/battle.ex
  apps/champions/lib/champions/battle/simulator.ex
  apps/champions/lib/champions/users.ex
  apps/champions/test/battle_test.exs
  apps/game_backend/lib/game_backend/units/skills/skill.ex
  apps/game_backend/lib/game_backend/users.ex
  apps/game_backend/lib/game_backend/users/unlock.ex
  apps/game_backend/lib/game_backend/users/upgrade.ex
  apps/game_backend/lib/game_backend/users/upgrades/buff.ex
  apps/game_backend/lib/game_backend/users/upgrades/upgrade_dependency.ex
  apps/game_backend/lib/game_backend/users/user.ex
  apps/game_backend/priv/repo/migrations/20240516155753_add_dungeon_upgrades_and_buffs.exs
  priv/repo/seeds.exs
Labels: autobattler

#650 [GH-636] Add purchase costs to items
  apps/game_backend/lib/game_backend/items.ex
  apps/game_backend/lib/game_backend/items/item_template.ex
  apps/game_backend/lib/game_backend/users/currencies.ex
  apps/game_backend/priv/items_templates.json
  apps/game_backend/priv/repo/migrations/20240527203024_add_purchase_costs_map_to_item_templates.exs
  apps/gateway/lib/gateway/controllers/curse_of_mirra/item_controller.ex
  apps/gateway/lib/gateway/controllers/fallback_controller.ex
  priv/repo/seeds.exs
Labels: champions
